# Site settings
author: Alan Coomes
title: Why I Decided to Study Software Engineering
header-img: img/home-bg.png
email: acoomes1@cord.edu
copyright_name: Alan Coomes
description: > # this means to ignore newlines until "baseurl:"
  The Beginnings
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  acoomes33

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
